# Generated by Django 4.0.6 on 2022-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_commande_client_commande_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('en cours de traiment', 'en cours de traitement'), ('non livre', 'non livre'), ('livre', 'livre')], max_length=200, null=True),
        ),
    ]
